Traceback (most recent call last):
  File "C:\Users\yoavp\Documents\projects\python_venvs\jupyter-book\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\yoavp\Documents\projects\python_venvs\jupyter-book\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\yoavp\Documents\projects\python_venvs\jupyter-book\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\yoavp\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\yoavp\Documents\projects\python_venvs\jupyter-book\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\yoavp\Documents\projects\python_venvs\jupyter-book\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\yoavp\Documents\projects\python_venvs\jupyter-book\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib
matplotlib.use("TkAgg")
from pyquibbler import initialize_quibbler, iquib
initialize_quibbler()
import matplotlib.pyplot as plt

x = iquib(0.5)
y = 1 - x
plt.plot([0, 1], [1, 0], '-')
plt.plot([0, x, x], [y, y, 0], '--', marker='D')
plt.title(x, fontsize=20)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
Cell [1;32mIn[3], line 4[0m
[0;32m      2[0m matplotlib[38;5;241m.[39muse([38;5;124m"[39m[38;5;124mTkAgg[39m[38;5;124m"[39m)
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyquibbler[39;00m [38;5;28;01mimport[39;00m initialize_quibbler, iquib
[1;32m----> 4[0m [43minitialize_quibbler[49m[43m([49m[43m)[49m
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      7[0m x [38;5;241m=[39m iquib([38;5;241m0.5[39m)

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\pyquibbler\utilities\input_validation_utils.py:56[0m, in [0;36mvalidate_user_input.<locals>._decorator.<locals>._wrapper[1;34m(*args, **kwargs)[0m
[0;32m     54[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(arg_values[38;5;241m.[39mget(var_name), expected_types):
[0;32m     55[0m         [38;5;28;01mraise[39;00m InvalidArgumentTypeException(var_name[38;5;241m=[39mvar_name, expected_type[38;5;241m=[39mexpected_types)
[1;32m---> 56[0m [38;5;28;01mreturn[39;00m func([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\pyquibbler\function_overriding\override_all.py:100[0m, in [0;36minitialize_quibbler[1;34m(draggable_plots, show_quibs_as_widgets, jupyterlab_extension)[0m
[0;32m     97[0m [38;5;28;01mif[39;00m is_quibbler_initialized():
[0;32m     98[0m     [38;5;28;01mreturn[39;00m
[1;32m--> 100[0m within_jupyterlab [38;5;241m=[39m jupyterlab_extension [38;5;129;01mand[39;00m [43mcreate_jupyter_project_if_in_jupyter_lab[49m[43m([49m[43m)[49m
[0;32m    102[0m func_definitions [38;5;241m=[39m create_definitions_for_python_functions()
[0;32m    103[0m [38;5;28;01mfor[39;00m func, func_definition [38;5;129;01min[39;00m func_definitions[38;5;241m.[39mitems():

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\pyquibbler\project\jupyer_project\jupyter_project.py:329[0m, in [0;36mcreate_jupyter_project_if_in_jupyter_lab[1;34m()[0m
[0;32m    327[0m project [38;5;241m=[39m JupyterProject[38;5;241m.[39mget_or_create()
[0;32m    328[0m project[38;5;241m.[39moverride_quib_persistence_functions()
[1;32m--> 329[0m [43mproject[49m[38;5;241;43m.[39;49m[43mlisten_for_events[49m[43m([49m[43m)[49m
[0;32m    330[0m project[38;5;241m.[39mget_save_within_notebook_state()
[0;32m    331[0m project[38;5;241m.[39mset_undo_redo_buttons_enable_state()

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\pyquibbler\project\jupyer_project\jupyter_project.py:272[0m, in [0;36mJupyterProject.listen_for_events[1;34m(self)[0m
[0;32m    264[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[0;32m    265[0m [38;5;124;03mListen for all events from frontend- this will create a callback for any event coming from the frontend,[39;00m
[0;32m    266[0m [38;5;124;03mand will run the relevant method for the event.[39;00m
[0;32m    267[0m [38;5;124;03mIt will then send BACK the response with the `request_id` specified in the original event[39;00m
[0;32m    268[0m [38;5;124;03m"""[39;00m
[0;32m    270[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpyquibbler[39;00m[38;5;21;01m.[39;00m[38;5;21;01moptional_packages[39;00m[38;5;21;01m.[39;00m[38;5;21;01mget_IPython[39;00m [38;5;28;01mimport[39;00m Comm
[1;32m--> 272[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_refresh_jupyter_notebook_path[49m[43m([49m[43m)[49m
[0;32m    273[0m [38;5;28mself[39m[38;5;241m.[39m_comm [38;5;241m=[39m Comm(target_name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mpyquibbler[39m[38;5;124m'[39m)
[0;32m    274[0m action_names_to_funcs [38;5;241m=[39m {
[0;32m    275[0m     [38;5;124m"[39m[38;5;124mundo[39m[38;5;124m"[39m: [38;5;28mself[39m[38;5;241m.[39mundo,
[0;32m    276[0m     [38;5;124m"[39m[38;5;124mredo[39m[38;5;124m"[39m: [38;5;28mself[39m[38;5;241m.[39mredo,
[1;32m   (...)[0m
[0;32m    282[0m     [38;5;124m"[39m[38;5;124mcleanup[39m[38;5;124m"[39m: [38;5;28mself[39m[38;5;241m.[39m_cleanup,
[0;32m    283[0m }

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\pyquibbler\project\jupyer_project\jupyter_project.py:212[0m, in [0;36mJupyterProject._refresh_jupyter_notebook_path[1;34m(self)[0m
[0;32m    210[0m [38;5;28;01mdef[39;00m [38;5;21m_refresh_jupyter_notebook_path[39m([38;5;28mself[39m):
[0;32m    211[0m     [38;5;28;01mtry[39;00m:
[1;32m--> 212[0m         [38;5;28mself[39m[38;5;241m.[39m_jupyter_notebook_path [38;5;241m=[39m [43mipynbname[49m[38;5;241;43m.[39;49m[43mpath[49m[43m([49m[43m)[49m
[0;32m    213[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mFileNotFoundError[39;00m:
[0;32m    214[0m         [38;5;28mself[39m[38;5;241m.[39m_jupyter_notebook_path [38;5;241m=[39m os[38;5;241m.[39menviron[38;5;241m.[39mget([38;5;124m"[39m[38;5;124mJUPYTER_NOTEBOOK[39m[38;5;124m"[39m)

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\ipynbname\__init__.py:89[0m, in [0;36mpath[1;34m()[0m
[0;32m     85[0m [38;5;28;01mdef[39;00m [38;5;21mpath[39m() [38;5;241m-[39m[38;5;241m>[39m Path:
[0;32m     86[0m [38;5;250m    [39m[38;5;124;03m""" Returns the absolute path of the notebook,[39;00m
[0;32m     87[0m [38;5;124;03m        or raises a FileNotFoundError exception if it cannot be determined.[39;00m
[0;32m     88[0m [38;5;124;03m    """[39;00m
[1;32m---> 89[0m     srv, path [38;5;241m=[39m [43m_find_nb_path[49m[43m([49m[43m)[49m
[0;32m     90[0m     [38;5;28;01mif[39;00m srv [38;5;129;01mand[39;00m path:
[0;32m     91[0m         root_dir [38;5;241m=[39m Path(srv[38;5;241m.[39mget([38;5;124m'[39m[38;5;124mroot_dir[39m[38;5;124m'[39m) [38;5;129;01mor[39;00m srv[[38;5;124m'[39m[38;5;124mnotebook_dir[39m[38;5;124m'[39m])

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\ipynbname\__init__.py:61[0m, in [0;36m_find_nb_path[1;34m()[0m
[0;32m     59[0m [38;5;28;01mdef[39;00m [38;5;21m_find_nb_path[39m() [38;5;241m-[39m[38;5;241m>[39m Union[Tuple[[38;5;28mdict[39m, PurePath], Tuple[[38;5;28;01mNone[39;00m, [38;5;28;01mNone[39;00m]]:
[0;32m     60[0m     [38;5;28;01mtry[39;00m:
[1;32m---> 61[0m         kernel_id [38;5;241m=[39m [43m_get_kernel_id[49m[43m([49m[43m)[49m
[0;32m     62[0m     [38;5;28;01mexcept[39;00m (MultipleInstanceError, [38;5;167;01mRuntimeError[39;00m):
[0;32m     63[0m         [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m, [38;5;28;01mNone[39;00m  [38;5;66;03m# Could not determine[39;00m

File [1;32m~\Documents\projects\python_venvs\jupyter-book\lib\site-packages\ipynbname\__init__.py:37[0m, in [0;36m_get_kernel_id[1;34m()[0m
[0;32m     34[0m [38;5;250m[39m[38;5;124;03m""" Returns the kernel ID of the ipykernel.[39;00m
[0;32m     35[0m [38;5;124;03m"""[39;00m
[0;32m     36[0m connection_file [38;5;241m=[39m Path(ipykernel[38;5;241m.[39mget_connection_file())[38;5;241m.[39mstem
[1;32m---> 37[0m kernel_id [38;5;241m=[39m [43mconnection_file[49m[38;5;241;43m.[39;49m[43msplit[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m-[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;241;43m1[39;49m[43m)[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m
[0;32m     38[0m [38;5;28;01mreturn[39;00m kernel_id

[1;31mIndexError[0m: list index out of range

